name: Build and Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  main:
    runs-on: ${{ matrix.image }}
    strategy:
      matrix:
        image: [macos-10.15, ubuntu-18.04, windows-2019]
    steps:
      - uses: actions/checkout@v2

      # RdGen
      - name: RdGen
        run: ./gradlew rdgen

      # Backend
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '3.1.101'
      - name: Build Backend
        run: dotnet build -c Release

      # Frontend
      - name: Test
        run: ./gradlew -PBuildConfiguration=Release -PbuildNumber=${{ github.run_id }} test
        env:
          LOCAL_ENV_RUN: true
          NO_FS_ROOTS_ACCESS_CHECK: true
      - name: Upload Test Results
        uses: actions/upload-artifact@v1.0.0
        with:
          name: ${{ runner.os }}.test-results
          path: build/reports/tests

      # Distribution
      - name: Build Distribution
        if: matrix.image == 'ubuntu-18.04'
        run: ./gradlew -PBuildConfiguration=Release -PbuildNumber=${{ github.run_id }} buildPlugin
      - name: Determine Version
        if: matrix.image == 'ubuntu-18.04'
        shell: pwsh
        run: |
          $version = ./scripts/Get-Version.ps1
          "AVALONIA_RIDER_VERSION=$version" | Out-File $env:GITHUB_ENV
      - name: Unpack Distribution # for the purpose of uploading
        if: matrix.image == 'ubuntu-18.04'
        shell: pwsh
        run: scripts/Unpack-Distribution.ps1
      - name: Upload Distribution
        if: matrix.image == 'ubuntu-18.04'
        uses: actions/upload-artifact@v2
        with:
          name: avaloniarider-${{ env.AVALONIA_RIDER_VERSION }}
          path: build/distributions/unpacked
